### ISSUE TITLE
PRF should never go below zero

### ISSUE THREAD

**Issue by benmontet** [benmontet/nutella#10]

**Comment by mirca** [comment]
For K2/Kepler data, we should add the "FLUX_BKG" to the tpf. That should ensure everything > 0

**Comment by benmontet** [comment]
To be clear, I'm fine with the entire flux going below zero! (Through a negative background presumably). But the pixel response function should never be negative, nor should the detector sensitivity (photons striking the detector should never lead to a decrease in total counts on any pixel)
