### ISSUE TITLE
Movement isn't quite right

### ISSUE THREAD

**Issue by benmontet** [benmontet/nutella#7]
In a simulated test with a simple PSF and no noise and no motion, it works perfectly and we get the ideal PSF back. 

As soon as we build in even simple motion, everything goes to hell. Why? Positions are not inferred correctly, need to explore to see what's going on (did we miss a minus sign somewhere?)

**Comment by benmontet** [comment]
Rectbivariatespline isn't quite working as expected. To move the perfect psf one pixel (in the model grid) is not a 0.25 pixel (in detector grid) shift! This is likely the cause of multiple issues. Will we have to create our own interpolating function? Perhaps!

**Comment by mirca** [comment]
oh, that's weird. I'm investigating that.

**Comment by benmontet** [comment]
I am too. It's surely something with the way we're doing the background
and/or calculating the likelihood.

When I do everything in linear space, including the minimization,
everything works as expected.

**Comment by benmontet** [comment]
Just pushed a new version, with everything working in linear space.

The issue is (was) (I think) that interpolating the flux in log space != to interpolating the flux in linear space, so the ending flux wasn't conserved (the shift would cause some flux to move up a pixel, and a nonequal amount of flux to remain in the primary pixel). Everything is actually in linear space in the telescope (although the detector effect is multiplicitive) so let's work in linear space for now. This is resolved as far as I'm concerned.

The perfect PSF works perfectly in the case where norm_super_psf is set to be exactly equal to one of the tpf cadences. It's not converging to the truth when we have a data-driven PSF, which is the next thing I will investigate.
