### ISSUE TITLE
better interpolation

### ISSUE THREAD

**Issue by benmontet** [benmontet/nutella#9]
I'm using a PSF which is a simple square of height one in the central 9 pixels, and motion that carries this only directly up and down. The norm_super_tpf *must* have sharp vertical edges in this case, as the columns outside the central 3 never receive any flux. 

This is what we're getting with RectBivariateSpline which clearly is an issue.
<img width="495" alt="screen shot 2017-12-06 at 9 24 12 pm" src="https://user-images.githubusercontent.com/1314530/33697330-04a04094-dacc-11e7-947b-3b9ae5e82c87.png">

**Comment by mirca** [comment]
Do you think that’s an issue with RectBivariateSpline itself or the way we are using it?

**Comment by benmontet** [comment]
It was an issue with the way we are using it, but we are now never using it. scipy ndimage shift is twice as fast.
